resolver: nightly-2020-06-25

packages:
  - .

extra-deps:
  - numhask-0.6.0.2
  #- PortMidi-0.1.5.2
  #- UISF-0.4.0.0
  #- arrows-0.4.4.2
  #- pure-fft-0.2.0
  #- Stream-0.4.7.2
  #- lazysmallcheck-0.6
  #- hmt-0.15
  #- lazy-csv-0.5.1
  #- multiset-comb-0.2.4.1
  #- permutation-0.5.0.5
  #- vivid-0.4.2.3
  #- vivid-osc-0.5.0.0
  #- vivid-supercollider-0.4.1.2
  - tidal-1.6.0

allow-newer: true
